version: '3.4'

networks:
  dev:
    driver: bridge

services:
  IoT.SmartZone:
    image: ${DOCKER_REGISTRY-}iotsmartzoneservicebootsrapper
    depends_on:
        - postgresDb
    container_name: bootsrapper
    ports:
        - 8081:80 
    build:
      context: .
      dockerfile: IoT.SmartZone.Service.Bootsrapper/Dockerfile
    environment: 
        - ASPNETCORE_ENVIRONMENT=Development
        - postgres__connectionString=Host=postgresDb;Port=5432;Database=postgres;Username=postgres;Password=qwe123
        - ASPNETCORE_URLS=http://+80
    networks:
        - dev

  postgresDb:
    image: postgres:latest
    container_name: postgresDB
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwe123
    restart: 
        always
    ports:
        - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data
    networks:
        - dev
volumes:
  postgres_data: